"""
ingest_new_sources.py — Ingest new PDFs into the project's data/sources/ pipeline.

Handles two modes:
  - native: PyMuPDF text extraction (fast, for digitized PDFs with embedded text)
  - ocr:    pytesseract page-by-page OCR (slow, for scanned image PDFs)

Usage:
    # Ingest both
    python scripts/ingest_new_sources.py

    # Single source
    python scripts/ingest_new_sources.py --id discoverie
    python scripts/ingest_new_sources.py --id de_occultis --ocr

    # OCR quality test (sample N pages before committing)
    python scripts/ingest_new_sources.py --id de_occultis --ocr --test 5
"""

import os
import sys
import json
import re
import argparse
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
log = logging.getLogger(__name__)

# ── project root ────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "sources"
MANIFEST = DATA_DIR / "source_manifest.json"

# ── chunking config ─────────────────────────────────────────────
CHUNK_SIZE = 25_000
CHUNK_OVERLAP = 500

# ── source definitions ──────────────────────────────────────────
SOURCES = {
    "discoverie": {
        "id": "discoverie",
        "label": "Reginald Scot — Discoverie of Witchcraft (1584 / 1886 reprint)",
        "path": r"c:\Users\akbon\Downloads\b21720307.pdf",
        "mode": "native",
        "description": (
            "Reginald Scot, The Discoverie of Witchcraft (1584). "
            "Digitized 1886 Nicholson reprint. Primary source for planetary angels, "
            "conjuring circles, spirit hierarchies, and sceptical analysis of magic. "
            "Directly cited in the Sphere of Hew Draper app (Book XV Ch. VII)."
        ),
    },
    "de_occultis": {
        "id": "de_occultis",
        "label": "Giambattista della Porta — De Occultis Literarum Notis (1592)",
        "path": r"c:\Users\akbon\Downloads\De Occultis Literarum Notis seu Artis.pdf",
        "mode": "ocr",
        "description": (
            "Giambattista della Porta, De Occultis Literarum Notis seu Artis "
            "Aenigmaticae (1592). The foundational Renaissance cryptography text. "
            "Covers substitution ciphers, digraphic ciphers, music ciphers, "
            "volvelle alphabet wheels, and steganography. The angelic 'characters' "
            "in Scot's Discoverie are generated by tracing names through "
            "planetary magic squares — a cipher system documented here."
        ),
        "ocr_lang": "lat+eng",  # Latin primary, some English headings
        "tesseract_cmd": r"C:\Program Files\Tesseract-OCR\tesseract.exe",
    },
}


# ══════════════════════════════════════════════════════════════════
# TEXT CLEANING
# ══════════════════════════════════════════════════════════════════

def clean_ocr_text(text: str) -> str:
    """Clean typical OCR artifacts from scanned PDFs."""
    # Collapse multiple spaces (common in archive.org scans)
    text = re.sub(r"[ \t]{2,}", " ", text)
    # Collapse 3+ newlines to double
    text = re.sub(r"\n{3,}", "\n\n", text)
    # Remove form-feed characters
    text = text.replace("\x0c", "\n\n")
    # Fix common OCR ligature errors
    text = text.replace("ﬁ", "fi").replace("ﬂ", "fl").replace("ﬀ", "ff")
    text = text.replace("ﬃ", "ffi").replace("ﬄ", "ffl")
    return text.strip()


def clean_native_text(text: str) -> str:
    """Clean text from PyMuPDF native extraction (usually just space normalization)."""
    text = re.sub(r"[ \t]{2,}", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = text.replace("\x0c", "\n\n")
    text = text.replace("ﬁ", "fi").replace("ﬂ", "fl").replace("ﬀ", "ff")
    return text.strip()


# ══════════════════════════════════════════════════════════════════
# TEXT EXTRACTION
# ══════════════════════════════════════════════════════════════════

def extract_native(pdf_path: str, progress: bool = True) -> str:
    """Extract embedded text from PDF using PyMuPDF."""
    import fitz
    doc = fitz.open(pdf_path)
    pages = []
    n = doc.page_count
    for i, page in enumerate(doc):
        if progress and i % 50 == 0:
            log.info("  Reading page %d/%d …", i + 1, n)
        text = page.get_text()
        if text.strip():
            pages.append(f"--- PAGE {i+1} ---\n{clean_native_text(text)}")
    doc.close()
    return "\n\n".join(pages)


def extract_ocr(pdf_path: str, tesseract_cmd: str, lang: str = "eng",
                max_pages: int | None = None, progress: bool = True) -> str:
    """OCR a scanned PDF page-by-page using pytesseract."""
    import fitz
    import pytesseract
    from PIL import Image
    import io

    pytesseract.pytesseract.tesseract_cmd = tesseract_cmd

    doc = fitz.open(pdf_path)
    n = doc.page_count if max_pages is None else min(max_pages, doc.page_count)
    pages = []

    for i in range(n):
        if progress and i % 10 == 0:
            log.info("  OCR page %d/%d …", i + 1, n)
        page = doc[i]
        # Render at 300 DPI for good OCR quality
        mat = fitz.Matrix(300 / 72, 300 / 72)
        pix = page.get_pixmap(matrix=mat, colorspace=fitz.csGRAY)
        img_data = pix.tobytes("png")
        img = Image.open(io.BytesIO(img_data))
        text = pytesseract.image_to_string(img, lang=lang)
        if text.strip():
            pages.append(f"--- PAGE {i+1} ---\n{clean_ocr_text(text)}")

    doc.close()
    return "\n\n".join(pages)


# ══════════════════════════════════════════════════════════════════
# CHUNKING
# ══════════════════════════════════════════════════════════════════

def chunk_text(text: str, chunk_size: int = CHUNK_SIZE,
               overlap: int = CHUNK_OVERLAP) -> list[tuple[str, int, int]]:
    """
    Split text into overlapping chunks, preferring paragraph breaks.
    Returns list of (chunk_text, start_char, end_char).
    """
    chunks = []
    pos = 0
    text_len = len(text)

    while pos < text_len:
        end = min(pos + chunk_size, text_len)

        if end < text_len:
            search_start = max(end - 2000, pos + chunk_size // 2)
            break_pos = text.rfind("\n\n", search_start, end)
            if break_pos > pos:
                end = break_pos + 2

        chunk = text[pos:end]
        chunks.append((chunk, pos, end))
        pos = end - overlap if end < text_len else text_len

    return chunks


# ══════════════════════════════════════════════════════════════════
# MANIFEST HELPERS
# ══════════════════════════════════════════════════════════════════

def load_manifest() -> dict:
    if MANIFEST.exists():
        with open(MANIFEST, "r", encoding="utf-8") as f:
            return json.load(f)
    return {"project": str(ROOT), "chunk_size": CHUNK_SIZE,
            "chunk_overlap": CHUNK_OVERLAP, "sources": []}


def save_manifest(manifest: dict):
    with open(MANIFEST, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
    log.info("Manifest updated: %s", MANIFEST)


def remove_source_from_manifest(manifest: dict, src_id: str):
    manifest["sources"] = [s for s in manifest["sources"] if s.get("id") != src_id]


# ══════════════════════════════════════════════════════════════════
# MAIN PIPELINE
# ══════════════════════════════════════════════════════════════════

def ingest_source(src_def: dict, force_ocr: bool = False,
                  ocr_test_pages: int | None = None) -> dict:
    """
    Full pipeline for one source:
      extract → chunk → write files → return manifest entry
    """
    src_id = src_def["id"]
    pdf_path = src_def["path"]
    mode = "ocr" if (force_ocr or src_def.get("mode") == "ocr") else "native"

    if not os.path.exists(pdf_path):
        log.error("File not found: %s", pdf_path)
        return {"id": src_id, "status": "missing", "path": pdf_path}

    # ── Extract ─────────────────────────────────────────────────
    log.info("Extracting [%s] mode=%s …", src_id, mode)

    if mode == "ocr":
        max_pages = ocr_test_pages  # None = all pages
        if ocr_test_pages:
            log.info("  TEST MODE: OCR first %d pages only", ocr_test_pages)
        text = extract_ocr(
            pdf_path,
            tesseract_cmd=src_def.get("tesseract_cmd",
                                      r"C:\Program Files\Tesseract-OCR\tesseract.exe"),
            lang=src_def.get("ocr_lang", "eng"),
            max_pages=max_pages,
        )
    else:
        text = extract_native(pdf_path)

    if not text.strip():
        log.warning("No text extracted from %s", src_id)
        return {"id": src_id, "status": "empty", "path": pdf_path}

    log.info("  Extracted %s chars", f"{len(text):,}")

    # ── Chunk ────────────────────────────────────────────────────
    chunks = chunk_text(text)
    log.info("  %d chunks of ~%d chars", len(chunks), CHUNK_SIZE)

    # ── Write ────────────────────────────────────────────────────
    chunk_dir = DATA_DIR / src_id
    chunk_dir.mkdir(parents=True, exist_ok=True)

    suffix = "_test" if ocr_test_pages else ""
    chunk_records = []
    for idx, (chunk_text_str, start, end) in enumerate(chunks):
        fname = f"chunk_{idx:03d}{suffix}.txt"
        fpath = chunk_dir / fname
        with open(fpath, "w", encoding="utf-8") as f:
            f.write(chunk_text_str)
        chunk_records.append({
            "chunk_id": idx,
            "file": str(fpath),
            "start_char": start,
            "end_char": end,
            "chars": len(chunk_text_str),
        })

    log.info("  Written to %s", chunk_dir)

    entry = {
        "id": src_id,
        "status": "ok" if not ocr_test_pages else "test_ocr",
        "label": src_def.get("label", src_id),
        "path": pdf_path,
        "description": src_def.get("description", ""),
        "mode": mode,
        "total_chars": len(text),
        "total_chunks": len(chunks),
        "chunk_dir": str(chunk_dir),
        "chunks": chunk_records,
    }
    if ocr_test_pages:
        entry["ocr_test_pages"] = ocr_test_pages

    return entry


def run(args):
    manifest = load_manifest()

    # Which sources to process
    if args.id:
        ids = [args.id]
    else:
        ids = list(SOURCES.keys())

    for src_id in ids:
        if src_id not in SOURCES:
            log.error("Unknown source id: %s (choices: %s)", src_id,
                      list(SOURCES.keys()))
            continue

        src_def = SOURCES[src_id]

        # Skip scanned PDFs unless --ocr explicitly given
        if src_def.get("mode") == "ocr" and not args.ocr:
            log.warning(
                "Skipping %s (scanned PDF). Re-run with --ocr to enable OCR. "
                "Use --test N to sample N pages first.",
                src_id,
            )
            continue

        entry = ingest_source(
            src_def,
            force_ocr=args.ocr,
            ocr_test_pages=args.test if args.test else None,
        )

        # Update manifest
        remove_source_from_manifest(manifest, src_id)
        manifest["sources"].append(entry)
        save_manifest(manifest)

        log.info("Done: %s — %s chunks", src_id,
                 entry.get("total_chunks", "?"))


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--id", help="Process only this source id")
    parser.add_argument("--ocr", action="store_true",
                        help="Enable OCR mode (for scanned PDFs)")
    parser.add_argument("--test", type=int, metavar="N",
                        help="OCR only the first N pages (quality test)")
    args = parser.parse_args()
    run(args)


if __name__ == "__main__":
    main()
